dbData:
  image: "ubuntu:14.04"
  volumes:
    - "/var/lib/mysql"
  command: "true"

db:
  image: "mysql:5.6"
  ports:
    - "3306"
  volumes_from:
      - "dbData"
  env_file:
    - 'env.db'

app:
  build: .
  command: bundle exec unicorn -p 3000
  volumes:
      - ".:/opt/app"
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - 'env.web'
