# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159f7958fb45f0fc8309d2f277be853a25b9c71f29a41522876a61b7f36fa33264058c9962346a3777ae8366b1fa18e3f9eb1a57c13f0bf2763e5db9c3f42059

test:
  secret_key_base: 0fabeb08595193fe3b21e9aba52f1b05cd1baa94efc756a3ae6acf1ba098977cc38ddda099afc669a0012ae196eab49b332c2bf26eeb9e313da788b406e6111a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
